# Generated by Django 5.2.17 on 2026-10-06 03:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ForumPost',
            fields=[
                ('author_username', models.CharField(max_length=100)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('DISCUSSION', 'Discussion'), ('QUESTION', 'Question'), ('OOTD', 'OOTD'), ('INSPO', 'Inspo')], default='DISCUSSION', max_length=20)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('image_caption', models.CharField(blank=True, max_length=200, null=True)),
                ('image_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_likes', models.IntegerField(default=0)),
                ('total_comments', models.IntegerField(default=0)),
            ],
        ),
    ]
